import { useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import classNames from 'classnames'
import CircularSlider from 'components/CircularSlider'

export default function Home() {
  const [values, setValues] = useState([
    { id: '1', label: 'label1', value: 10, color: 'cherry' },
    { id: '2', label: 'label2', value: 10, color: 'kiwi' },
    { id: '3', label: 'label3', value: 80, color: 'blueberry' },
  ])
  const onChange = (newValue) => {
    setValues((values) =>
      values.map((value, index) => ({
        ...value,
        ...newValue.find(({ id }) => id === value.id),
      }))
    )
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CircularSlider
          label="Slider"
          segments={values}
          radio={122}
          onChange={onChange}
          maxSegment={100}
          minSegment={5}
        />
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
